version: "3"

services:
  server:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: "root"
      DB_PASSWORD: "root"
      DB_NAME: "pixiepot"
    ports:
      - "4001:3001"
    volumes:
      - ./server:/server

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: pixiepot
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db-data:/var/lib/postgresql/data
